/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Conexiones.Conexion;
import Main.CambiarInterfaz;
import javax.swing.JOptionPane;

/**
 *
 * @author NICOLAS
 */
public class Calificaciones extends javax.swing.JFrame {

    /**
     * Creates new form Calificaciones
     */
    public Calificaciones() {
        initComponents();
        setLayout(null);
        setTitle("Calificaciones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNota1 = new javax.swing.JLabel();
        lblNota2 = new javax.swing.JLabel();
        lblNota3 = new javax.swing.JLabel();
        lblNota4 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        txtNota4 = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblElije = new javax.swing.JLabel();
        comboElije = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        comboMaterias = new javax.swing.JComboBox<>();
        lblMaterias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRut.setText("Rut(Obligatorio)");

        jLabel2.setText("Ingrese el rut del alumno para poder identificarlo:");

        jLabel4.setText("Asignar Calificaciones");

        lblNota1.setText("Nota 1");

        lblNota2.setText("Nota 2");

        lblNota3.setText("Nota 3");

        lblNota4.setText("Nota 4");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblElije.setText("Elije");

        comboElije.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresar Notas", "Mostrar Alumno" }));
        comboElije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboElijeActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        comboMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Fundamento de Psicologia", "Psicoanalisis", "Neurobiologia", "Fundamento de Programacion", "Fundamento de Base de Datos", "Fundamento de Sistemas Operativos", "Anatomia", "Fisiologia", "Farmacologia" }));

        lblMaterias.setText("Materias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblElije)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboElije, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegresar)
                            .addComponent(lblMaterias)))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRut)
                        .addGap(48, 48, 48)
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNota2)
                                    .addComponent(lblNota3)
                                    .addComponent(lblNota4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNota3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtNota2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNota1)
                                .addGap(25, 25, 25)
                                .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(comboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(btnAceptar)))))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRut)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblElije)
                            .addComponent(comboElije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblMaterias))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNota1)
                            .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNota2)
                            .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNota3)
                                    .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNota4)
                                    .addComponent(txtNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        CambiarInterfaz cam = new CambiarInterfaz();
        cam.regresarMenu();
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void comboElijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboElijeActionPerformed
        //aqui al elegir eliminar o mostrar alumno
        //las casillas para agregar se deshabilitaran
        if (comboElije.getSelectedItem() == "Mostrar Alumno") {
            txtNota1.setEnabled(false);
            txtNota2.setEnabled(false);
            txtNota3.setEnabled(false);
            txtNota4.setEnabled(false);
        }
        //aca sucede lo contrario de arriba, se habilitaran.
        if (comboElije.getSelectedItem() == "Ingresar Notas") {
            txtNota1.setEnabled(true);
            txtNota2.setEnabled(true);
            txtNota3.setEnabled(true);
            txtNota4.setEnabled(true);
        }
    }//GEN-LAST:event_comboElijeActionPerformed

    
    
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String rut = "";
        String nota1 = "";
        String nota2 = "";
        String nota3 = "";
        String nota4 = "";
        String materia = "";
        
        int idMateria = 0;
        
        rut = txtRut.getText();
        nota1 = txtNota1.getText();
        nota2 = txtNota2.getText();
        nota3 = txtNota3.getText();
        nota4 = txtNota4.getText();
        materia = comboMaterias.getSelectedItem().toString();
        
        String opcionCombo = (String)comboElije.getSelectedItem();
        
        //dependiendo de la materia adquiere un id
        if (materia.equals("Fundamento de Psicologia")) {
            idMateria = 1;
        }if (materia.equals("Psicoanalisis")) {
            idMateria = 2;
        }
        if (materia.equals("Neurobiologia")) {
            idMateria = 3;
        }
        if (materia.equals("Fundamento de Programacion")) {
            idMateria = 4;
        }
        if (materia.equals("Fundamento de Base de Datos")) {
            idMateria = 5;
        }
        if (materia.equals("Fundamento de Sistemas Operativos")) {
            idMateria = 6;
        }
        if (materia.equals("Anatomia")) {
            idMateria = 7;
        }
        if (materia.equals("Fisiologia")) {
            idMateria = 8;
        }
        if (materia.equals("Farmacologiaa")) {
            idMateria = 9;
        }
        
        
        //mensaje de un rut vacio y mostrar alumno
        if (opcionCombo.equals("Mostrar Alumno")) {
            if (rut.equals("")) {
                JOptionPane.showMessageDialog(null, "Complete el campo: RUT");
            } else {
                Conexion con = new Conexion();
                int rutnum = Integer.parseInt(rut);
                
                //agregamos al txtarea
                txtArea.append(con.mostrarCalificacionesAlumno(rutnum));
                
            }
        }
        
        
        if (opcionCombo.equals("Ingresar Notas")) {
            if (rut.equals("") || nota1.equals("") || nota2.equals("") || nota3.equals("") || nota4.equals("") || materia.equals("...")) {
                JOptionPane.showMessageDialog(null, "Relleno los compos faltantes");
            } else {
                Conexion con = new Conexion();
                
                int elrut = Integer.parseInt(rut);
                double cal1 = Double.parseDouble(nota1);
                double cal2 = Double.parseDouble(nota2);
                double cal3 = Double.parseDouble(nota3);
                double cal4 = Double.parseDouble(nota4);
                
                con.ingresarNotasAlumno(elrut, idMateria, cal1, cal2, cal3, cal4);
                
                
                JOptionPane.showMessageDialog(null, "Rut: "+rut+ ""
                                + "\nMateria: "+materia+""
                                + "\nNota 1: "+nota1+""
                                + "\nNota 2: "+nota2+""
                                + "\nNota 3: "+nota3+""
                                + "\nNota 4: "+nota4);
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboElije;
    private javax.swing.JComboBox<String> comboMaterias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblElije;
    private javax.swing.JLabel lblMaterias;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblNota2;
    private javax.swing.JLabel lblNota3;
    private javax.swing.JLabel lblNota4;
    private javax.swing.JLabel lblRut;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtNota4;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
